/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonBarang1 = new javax.swing.JRadioButton();
        jRadioButtonBarang2 = new javax.swing.JRadioButton();
        jRadioButtonBarang3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldHargaBarang1 = new javax.swing.JTextField();
        jTextFieldHargaBarang2 = new javax.swing.JTextField();
        jTextFieldHargaBarang3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldJumlahBarang1 = new javax.swing.JTextField();
        jTextFieldJumlahBarang2 = new javax.swing.JTextField();
        jTextFieldJumlahBarang3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldHargaBarangDiskon1 = new javax.swing.JTextField();
        jTextFieldHargaBarangDiskon2 = new javax.swing.JTextField();
        jTextFieldHargaBarangDiskon3 = new javax.swing.JTextField();
        jTextFieldTotalHarga1 = new javax.swing.JTextField();
        jTextFieldTotalHarga2 = new javax.swing.JTextField();
        jTextFieldTotalHarga3 = new javax.swing.JTextField();
        jTextFieldTotalPembayaran = new javax.swing.JTextField();
        jTextFieldDiskon = new javax.swing.JTextField();
        jTextFieldPembayaran = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonTotall = new javax.swing.JButton();
        jTextFieldBayar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldUangAkhir = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButtonUangAkhir = new javax.swing.JButton();
        jButtonHapusSemua = new javax.swing.JButton();
        jButtonKeluar = new javax.swing.JButton();

        jRadioButtonBarang1.setText("Barang 1");
        jRadioButtonBarang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBarang1ActionPerformed(evt);
            }
        });

        jRadioButtonBarang2.setText("Barang 2");

        jRadioButtonBarang3.setText("Barang 3");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Harga Barang");

        jTextFieldHargaBarang1.setEditable(false);
        jTextFieldHargaBarang1.setBackground(new java.awt.Color(204, 204, 255));
        jTextFieldHargaBarang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHargaBarang1ActionPerformed(evt);
            }
        });

        jTextFieldHargaBarang2.setEditable(false);
        jTextFieldHargaBarang2.setBackground(new java.awt.Color(204, 204, 255));

        jTextFieldHargaBarang3.setEditable(false);
        jTextFieldHargaBarang3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Jumlah Barang");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel3.setText("MINI KASIR");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Harga Barang Diskon");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Total Harga");

        jTextFieldHargaBarangDiskon1.setEditable(false);
        jTextFieldHargaBarangDiskon1.setBackground(new java.awt.Color(204, 204, 255));

        jTextFieldHargaBarangDiskon2.setEditable(false);
        jTextFieldHargaBarangDiskon2.setBackground(new java.awt.Color(204, 204, 255));

        jTextFieldHargaBarangDiskon3.setEditable(false);
        jTextFieldHargaBarangDiskon3.setBackground(new java.awt.Color(204, 204, 255));

        jTextFieldTotalPembayaran.setEditable(false);
        jTextFieldTotalPembayaran.setBackground(new java.awt.Color(204, 204, 255));

        jTextFieldDiskon.setEditable(false);
        jTextFieldDiskon.setBackground(new java.awt.Color(204, 204, 255));

        jTextFieldPembayaran.setEditable(false);
        jTextFieldPembayaran.setBackground(new java.awt.Color(204, 204, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Total Pembayaran");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Diskon 5% Jika Pembelian Diatas 1.000.000");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Pembayaran Setelah Diskon");

        jButtonTotall.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonTotall.setText("Total");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Bayar");

        jTextFieldUangAkhir.setEditable(false);
        jTextFieldUangAkhir.setBackground(new java.awt.Color(204, 204, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Uang Akhir");

        jButtonUangAkhir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonUangAkhir.setText("Uang Akhir");

        jButtonHapusSemua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonHapusSemua.setText("Hapus Semua");

        jButtonKeluar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonKeluar.setText("Keluar");
        jButtonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonTotall))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(163, 163, 163)
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButtonBarang1)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextFieldHargaBarang1))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButtonBarang2)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextFieldHargaBarang2))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(90, 90, 90)
                                                .addComponent(jLabel1))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButtonBarang3)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextFieldHargaBarang3)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextFieldJumlahBarang1)
                                            .addComponent(jTextFieldJumlahBarang3)
                                            .addComponent(jTextFieldJumlahBarang2))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextFieldHargaBarangDiskon1)
                                            .addComponent(jTextFieldHargaBarangDiskon3)
                                            .addComponent(jTextFieldHargaBarangDiskon2)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel6))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jButtonHapusSemua)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel10)))))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButtonKeluar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonUangAkhir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldUangAkhir)
                            .addComponent(jTextFieldPembayaran)
                            .addComponent(jTextFieldDiskon, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldTotalPembayaran)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldTotalHarga1)
                            .addComponent(jTextFieldTotalHarga3)
                            .addComponent(jTextFieldTotalHarga2)
                            .addComponent(jTextFieldBayar, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonBarang1)
                    .addComponent(jTextFieldHargaBarang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldJumlahBarang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHargaBarangDiskon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTotalHarga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonBarang2)
                    .addComponent(jTextFieldHargaBarang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldJumlahBarang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHargaBarangDiskon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTotalHarga2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonBarang3)
                    .addComponent(jTextFieldHargaBarang3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldJumlahBarang3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHargaBarangDiskon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTotalHarga3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTotalPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonTotall)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUangAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jButtonHapusSemua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonUangAkhir)
                    .addComponent(jButtonKeluar)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonBarang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBarang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonBarang1ActionPerformed

    private void jButtonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonKeluarActionPerformed

    private void jTextFieldHargaBarang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHargaBarang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHargaBarang1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHapusSemua;
    private javax.swing.JButton jButtonKeluar;
    private javax.swing.JButton jButtonTotall;
    private javax.swing.JButton jButtonUangAkhir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButtonBarang1;
    private javax.swing.JRadioButton jRadioButtonBarang2;
    private javax.swing.JRadioButton jRadioButtonBarang3;
    private javax.swing.JTextField jTextFieldBayar;
    private javax.swing.JTextField jTextFieldDiskon;
    private javax.swing.JTextField jTextFieldHargaBarang1;
    private javax.swing.JTextField jTextFieldHargaBarang2;
    private javax.swing.JTextField jTextFieldHargaBarang3;
    private javax.swing.JTextField jTextFieldHargaBarangDiskon1;
    private javax.swing.JTextField jTextFieldHargaBarangDiskon2;
    private javax.swing.JTextField jTextFieldHargaBarangDiskon3;
    private javax.swing.JTextField jTextFieldJumlahBarang1;
    private javax.swing.JTextField jTextFieldJumlahBarang2;
    private javax.swing.JTextField jTextFieldJumlahBarang3;
    private javax.swing.JTextField jTextFieldPembayaran;
    private javax.swing.JTextField jTextFieldTotalHarga1;
    private javax.swing.JTextField jTextFieldTotalHarga2;
    private javax.swing.JTextField jTextFieldTotalHarga3;
    private javax.swing.JTextField jTextFieldTotalPembayaran;
    private javax.swing.JTextField jTextFieldUangAkhir;
    // End of variables declaration//GEN-END:variables
}
