/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonBarang1 = new javax.swing.JRadioButton();
        jRadioButtonBarang2 = new javax.swing.JRadioButton();
        jRadioButtonBarang3 = new javax.swing.JRadioButton();
        jLabel = new javax.swing.JLabel();
        jTextFieldHargaBarang1 = new javax.swing.JTextField();
        jTextFieldHargaBarang2 = new javax.swing.JTextField();
        jTextFieldHargaBarang3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldJumlahBarang1 = new javax.swing.JTextField();
        jTextFieldJumlahBarang2 = new javax.swing.JTextField();
        jTextFieldJumlahBarang3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldHargaBarangDiskon1 = new javax.swing.JTextField();
        jTextFieldHargaBarangDiskon2 = new javax.swing.JTextField();
        jTextFieldHargaBarangDiskon3 = new javax.swing.JTextField();
        jTextFieldTotalHarga1 = new javax.swing.JTextField();
        jTextFieldTotalHarga2 = new javax.swing.JTextField();
        jTextFieldTotalHarga3 = new javax.swing.JTextField();
        jTextFieldTotalPembayaran = new javax.swing.JTextField();
        jTextFieldDiskon = new javax.swing.JTextField();
        jTextFieldPembayaran = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonTotal = new javax.swing.JButton();
        jTextFieldBayar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldUangAkhir = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButtonUangAkhir = new javax.swing.JButton();
        jButtonHapusSemua = new javax.swing.JButton();
        jButtonKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRadioButtonBarang1.setText("Barang 1");
        jRadioButtonBarang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBarang1ActionPerformed(evt);
            }
        });

        jRadioButtonBarang2.setText("Barang 2");

        jRadioButtonBarang3.setText("Barang 3");

        jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel.setText("Harga Barang");

        jTextFieldHargaBarang1.setEditable(false);
        jTextFieldHargaBarang1.setBackground(new java.awt.Color(204, 204, 255));
        jTextFieldHargaBarang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHargaBarang1ActionPerformed(evt);
            }
        });

        jTextFieldHargaBarang2.setEditable(false);
        jTextFieldHargaBarang2.setBackground(new java.awt.Color(204, 204, 255));

        jTextFieldHargaBarang3.setEditable(false);
        jTextFieldHargaBarang3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Jumlah Barang");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel2.setText("MINI KASIR");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Harga Barang Diskon");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Total Harga");

        jTextFieldHargaBarangDiskon1.setEditable(false);
        jTextFieldHargaBarangDiskon1.setBackground(new java.awt.Color(204, 204, 255));

        jTextFieldHargaBarangDiskon2.setEditable(false);
        jTextFieldHargaBarangDiskon2.setBackground(new java.awt.Color(204, 204, 255));

        jTextFieldHargaBarangDiskon3.setEditable(false);
        jTextFieldHargaBarangDiskon3.setBackground(new java.awt.Color(204, 204, 255));

        jTextFieldTotalHarga2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalHarga2ActionPerformed(evt);
            }
        });

        jTextFieldTotalPembayaran.setEditable(false);
        jTextFieldTotalPembayaran.setBackground(new java.awt.Color(204, 204, 255));

        jTextFieldDiskon.setEditable(false);
        jTextFieldDiskon.setBackground(new java.awt.Color(204, 204, 255));

        jTextFieldPembayaran.setEditable(false);
        jTextFieldPembayaran.setBackground(new java.awt.Color(204, 204, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Total Pembayaran");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Diskon 5% Jika Pembelian Diatas 1.000.000");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Pembayaran Setelah Diskon");

        jButtonTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonTotal.setText("Total");
        jButtonTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTotalActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Bayar");

        jTextFieldUangAkhir.setEditable(false);
        jTextFieldUangAkhir.setBackground(new java.awt.Color(204, 204, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Uang Akhir");

        jButtonUangAkhir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonUangAkhir.setText("Uang Akhir");

        jButtonHapusSemua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonHapusSemua.setText("Hapus Semua");

        jButtonKeluar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonKeluar.setText("Keluar");
        jButtonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(569, 569, 569)
                            .addComponent(jButtonTotal))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(157, 157, 157)
                                            .addComponent(jLabel2)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jRadioButtonBarang1)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jTextFieldHargaBarang1))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jRadioButtonBarang2)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jTextFieldHargaBarang2))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(90, 90, 90)
                                                    .addComponent(jLabel))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jRadioButtonBarang3)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jTextFieldHargaBarang3)))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextFieldJumlahBarang1)
                                                .addComponent(jTextFieldJumlahBarang3)
                                                .addComponent(jTextFieldJumlahBarang2))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextFieldHargaBarangDiskon1)
                                                .addComponent(jTextFieldHargaBarangDiskon3)
                                                .addComponent(jTextFieldHargaBarangDiskon2)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGap(0, 0, Short.MAX_VALUE)
                                                    .addComponent(jLabel5))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jButtonHapusSemua)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel9)))))
                                    .addGap(18, 18, 18))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonKeluar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonUangAkhir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldUangAkhir)
                                .addComponent(jTextFieldPembayaran)
                                .addComponent(jTextFieldDiskon, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextFieldTotalPembayaran)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldTotalHarga1)
                                .addComponent(jTextFieldTotalHarga3)
                                .addComponent(jTextFieldTotalHarga2)
                                .addComponent(jTextFieldBayar, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addGap(8, 8, 8)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(jLabel2)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonBarang1)
                        .addComponent(jTextFieldHargaBarang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldJumlahBarang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldHargaBarangDiskon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldTotalHarga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonBarang2)
                        .addComponent(jTextFieldHargaBarang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldJumlahBarang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldHargaBarangDiskon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldTotalHarga2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonBarang3)
                        .addComponent(jTextFieldHargaBarang3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldJumlahBarang3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldHargaBarangDiskon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldTotalHarga3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldTotalPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGap(9, 9, 9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jButtonTotal)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldUangAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jButtonHapusSemua))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonUangAkhir)
                        .addComponent(jButtonKeluar))
                    .addGap(6, 6, 6)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonBarang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBarang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonBarang1ActionPerformed

    private void jTextFieldHargaBarang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHargaBarang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHargaBarang1ActionPerformed

    private void jButtonTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTotalActionPerformed
        // TODO add your handling code here:
        double jumlahbarang1 = 0, jumlahbarang2 = 0, jumlahbarang3 = 0, byr = 0, hb1, hb2, hb3, diskon = 0.01, total, hargadiskon;
                hb1 = Double.parseDouble(jTextFieldHargaBarang1.getText());
                hb2 = Double.parseDouble(jTextFieldHargaBarang2.getText());
                hb3 = Double.parseDouble(jTextFieldHargaBarang3.getText());
                try{
                    jumlahbarang1 = Double.parseDouble(jTextFieldJumlahBarang1.getText());
                    jumlahbarang2 = Double.parseDouble(jTextFieldJumlahBarang2.getText());
                    jumlahbarang3 = Double.parseDouble(jTextFieldJumlahBarang3.getText());
                }
                catch (Exception error){
                    showMessageDialog(null, "Tidak Boleh Kosong");
                }
                
                if (jumlahbarang1 >= 50){
                    total = hb1 * jumlahbarang1 - diskon;
                    hargadiskon = hb1 * diskon;
                    jTextFieldTotalHarga1.setText(String.valueOf(total));
                    jTextFieldHargaBarangDiskon1.setText(String.valueOf(hargadiskon));
                }else {
                    total = hb1 * jumlahbarang1;
                    jTextFieldTotalHarga1.setText(String.valueOf(total));
                }
                
                if (jumlahbarang2 >= 50){
                    total = hb2 * jumlahbarang1 - diskon;
                    hargadiskon = hb2 * diskon;
                    jTextFieldTotalHarga2.setText(String.valueOf(total));
                    jTextFieldHargaBarangDiskon2.setText(String.valueOf(hargadiskon));
                }else {
                    total = hb2 * jumlahbarang2;
                    jTextFieldTotalHarga2.setText(String.valueOf(total));
                }
                
                if (jumlahbarang3 >= 50){
                    total = hb3 * jumlahbarang1 - diskon;
                    hargadiskon = hb3 * diskon;
                    jTextFieldTotalHarga3.setText(String.valueOf(total));
                    jTextFieldHargaBarangDiskon3.setText(String.valueOf(hargadiskon));
                }else {
                    total = hb3 * jumlahbarang3;
                    jTextFieldTotalHarga3.setText(String.valueOf(total));
                }
                
                double th1, th2, th3, tp, hasildiskon5 = 0, diskon5 = 0.05, hasildiskon;
                th1 = Double.parseDouble(jTextFieldTotalHarga1.getText());
                th2 = Double.parseDouble(jTextFieldTotalHarga2.getText());
                th3 = Double.parseDouble(jTextFieldTotalHarga3.getText());
                tp = th1 + th2 + th3;
                jTextFieldTotalPembayaran.setText(String.valueOf(tp));
                if(tp >= 1000000){
                    hasildiskon5 = tp * diskon5;
                    jTextFieldDiskon.setText(String.valueOf(hasildiskon5));
                    hasildiskon = tp - hasildiskon5;
                    jTextFieldPembayaran.setText(String.valueOf(hasildiskon));
                }else{
                    jTextFieldPembayaran.setText(String.valueOf(tp));
                }
    }//GEN-LAST:event_jButtonTotalActionPerformed

    private void jButtonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonKeluarActionPerformed

    private void jTextFieldTotalHarga2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalHarga2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalHarga2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHapusSemua;
    private javax.swing.JButton jButtonKeluar;
    private javax.swing.JButton jButtonTotal;
    private javax.swing.JButton jButtonUangAkhir;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButtonBarang1;
    private javax.swing.JRadioButton jRadioButtonBarang2;
    private javax.swing.JRadioButton jRadioButtonBarang3;
    private javax.swing.JTextField jTextFieldBayar;
    private javax.swing.JTextField jTextFieldDiskon;
    private javax.swing.JTextField jTextFieldHargaBarang1;
    private javax.swing.JTextField jTextFieldHargaBarang2;
    private javax.swing.JTextField jTextFieldHargaBarang3;
    private javax.swing.JTextField jTextFieldHargaBarangDiskon1;
    private javax.swing.JTextField jTextFieldHargaBarangDiskon2;
    private javax.swing.JTextField jTextFieldHargaBarangDiskon3;
    private javax.swing.JTextField jTextFieldJumlahBarang1;
    private javax.swing.JTextField jTextFieldJumlahBarang2;
    private javax.swing.JTextField jTextFieldJumlahBarang3;
    private javax.swing.JTextField jTextFieldPembayaran;
    private javax.swing.JTextField jTextFieldTotalHarga1;
    private javax.swing.JTextField jTextFieldTotalHarga2;
    private javax.swing.JTextField jTextFieldTotalHarga3;
    private javax.swing.JTextField jTextFieldTotalPembayaran;
    private javax.swing.JTextField jTextFieldUangAkhir;
    // End of variables declaration//GEN-END:variables
}